# Change these first
owner: jacobjuneau6 # Your GitHub organization or username, where this repository lives
repo: urban-octo-rotary-phone # The name of this repository

sites:
  - name: test
    url: 75.63.94.133

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
